<?php

namespace ContainerVUFdqDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j7LfHbh.App\Controller\EmployeeController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.j7LfHbh'] ?? $container->load('get_ServiceLocator_J7LfHbhService'));

        if (isset($container->privates['.service_locator.j7LfHbh.App\\Controller\\EmployeeController::edit()'])) {
            return $container->privates['.service_locator.j7LfHbh.App\\Controller\\EmployeeController::edit()'];
        }

        return $container->privates['.service_locator.j7LfHbh.App\\Controller\\EmployeeController::edit()'] = $a->withContext('App\\Controller\\EmployeeController::edit()', $container);
    }
}
