<?php

namespace Container6Qw4rEg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerfilterAjaxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RjHTMD1.App\Controller\EmployeeController::filterAjax()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RjHTMD1.App\\Controller\\EmployeeController::filterAjax()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'employee' => ['privates', '.errored..service_locator.RjHTMD1.App\\Entity\\Employee', NULL, 'Cannot autowire service ".service_locator.RjHTMD1": it needs an instance of "App\\Entity\\Employee" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'employee' => 'App\\Entity\\Employee',
        ]))->withContext('App\\Controller\\EmployeeController::filterAjax()', $container);
    }
}
