<?php

namespace Container6Qw4rEg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RjHTMD1.App\Entity\Employee' shared service.
     *
     * @return \App\Entity\Employee
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RjHTMD1": it needs an instance of "App\\Entity\\Employee" but this type has been excluded in "config/services.yaml".');
    }
}
