<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVUFdqDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVUFdqDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVUFdqDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVUFdqDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVUFdqDx\App_KernelDevDebugContainer([
    'container.build_hash' => 'VUFdqDx',
    'container.build_id' => 'e37402ae',
    'container.build_time' => 1741321569,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVUFdqDx');
