<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNB8Re4m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNB8Re4m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNB8Re4m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNB8Re4m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNB8Re4m\App_KernelDevDebugContainer([
    'container.build_hash' => 'NB8Re4m',
    'container.build_id' => 'bb0ce55e',
    'container.build_time' => 1740751399,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNB8Re4m');
