<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExwy9xV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExwy9xV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExwy9xV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExwy9xV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerExwy9xV\App_KernelDevDebugContainer([
    'container.build_hash' => 'Exwy9xV',
    'container.build_id' => 'db87bf9b',
    'container.build_time' => 1740576782,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExwy9xV');
