<?php

namespace ContainerNB8Re4m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vkpg2BMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vkpg2BM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vkpg2BM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\EmployeeController::edit' => ['privates', '.service_locator.j7LfHbh.App\\Controller\\EmployeeController::edit()', 'getEmployeeControllereditService', true],
            'App\\Controller\\EmployeeController::delete' => ['privates', '.service_locator.j7LfHbh.App\\Controller\\EmployeeController::delete()', 'getEmployeeControllerdeleteService', true],
            'App\\Controller\\EmployeeController::filterAjax' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\EmployeeController::filterAjax()', 'getEmployeeControllerfilterAjaxService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\EmployeeController:edit' => ['privates', '.service_locator.j7LfHbh.App\\Controller\\EmployeeController::edit()', 'getEmployeeControllereditService', true],
            'App\\Controller\\EmployeeController:delete' => ['privates', '.service_locator.j7LfHbh.App\\Controller\\EmployeeController::delete()', 'getEmployeeControllerdeleteService', true],
            'App\\Controller\\EmployeeController:filterAjax' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\EmployeeController::filterAjax()', 'getEmployeeControllerfilterAjaxService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\EmployeeController::edit' => '?',
            'App\\Controller\\EmployeeController::delete' => '?',
            'App\\Controller\\EmployeeController::filterAjax' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\EmployeeController:edit' => '?',
            'App\\Controller\\EmployeeController:delete' => '?',
            'App\\Controller\\EmployeeController:filterAjax' => '?',
        ]);
    }
}
