<?php

namespace ContainerFf0MZEh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EmployeeType' shared autowired service.
     *
     * @return \App\Form\EmployeeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EmployeeType.php';

        return $container->privates['App\\Form\\EmployeeType'] = new \App\Form\EmployeeType(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
